firefly-iii/kubernetes

firefly-iii.yaml
This is needed to get https urls when running nginx ingress with cert-manager
@JC5
=> Trust nginx ingress

firefly-iii.yaml
The extra whitespace in the YAML separator causes Kustomize to ignore the deployment object.
@JC5
=> Remove invalid whitespace

firefly-iii.yaml
Hello @JC5,
This fixes no known issue.
- Updating upload path from `/var/www/firefly-iii/storage/upload` to `/var/www/html/firefly-iii/storage/upload` as present in Docker image
- Removing export persistent volume claim directory and mounting
- Do some space (it was very condensed)
- Now we can directly access to Firefly-III on port 80
I getting in direction that you want to change your project directory from `/var/www/firefly-iii` to `/var/www/html/firefly-iii` in Docker images: your whole project is into this `html/` directory, but it's still existing a `storage` directory:
```
root@firefly-iii:/var/www# ls firefly-iii/ firefly-iii/storage/ html/
firefly-iii/:
storage
firefly-iii/storage/:
export	upload
html/:
COPYING  Procfile  app.json  bootstrap …
```
=> Updating yaml file for Kubernetes deployment

firefly-iii-csv.yaml, firefly-iii.yaml, ingress-firefly-iii-csv.yaml, ingress-firefly-iii.yaml, kustomization.yaml, mysql.yaml, pv-firefly-iii-mysql.yaml.example, pv-firefly-iii.yaml.example
- added csv-importer pod
- added ingress (tls) support
- switched to latest alpine based mariadb
- added (example) definitions for persistent volumes.
@JC5
=> Small fixes to run on current k8s

firefly-iii-importer.yaml, ingress-firefly-iii-importer.yaml
- The CSV Importer has been archived (https://github.com/firefly-iii/csv-importer) and replaced by the Data Importer. This PR updates the k8s manifests accordingly.
@JC5
=> replace csv samples with new data importer

helm/Chart.yaml, helm/README.md, helm/charts/firefly-csv/Chart.yaml, helm/charts/firefly-csv/README.md, helm/charts/firefly-csv/templates/firefly-csv-ing.yaml, helm/charts/firefly-csv/templates/firefly-csv-pvc.yml, helm/charts/firefly-csv/values.yaml, helm/charts/firefly-db/Chart.yaml, helm/charts/firefly-db/README.md, helm/charts/firefly-db/templates/firefly-db-pvc.yml, helm/charts/firefly-db/values.yaml, helm/charts/firefly-iii/Chart.yaml, helm/charts/firefly-iii/README.md, helm/charts/firefly-iii/templates/firefly-iii-ing.yaml, helm/charts/firefly-iii/templates/firefly-iii-pvc.yaml, helm/charts/firefly-iii/values.yaml
This is the first PR in a series of PRs to bring the helm charts up to version 1.0.0
Changes are explained in more detail in the commit message if needed.
For the `firefly-csv` chart, I'm aware that it needs to be updated for the importer. This will happen in one of the next PRs.
- fix: subcharts are only used when they are enabled in the config
- breaking feature change: ingress annotations are configurable now (this is needed to make the chart usable in some environments, e.g. cert-manager issuer annotations)
- breaking feature change: update storage class and access mode to more widely used values.
- feat: add support for `ingress.spec.ingressClassName` 
@JC5
=> Update helm chart 

charts/README.md, charts/firefly-iii-stack/Chart.yaml
:warning: #20 must be merged before this PR is merged!
This updates the URLs of the dependencies to the ones that are available after the merge of #20, eliminating the need to clone the repository to use the charts.
@JC5
=> chore: switch to packaged dependencies

charts/firefly-db/Chart.yaml, charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii/Chart.yaml, charts/importer/Chart.yaml
This bumps the versions of all charts to trigger a new release and switches back to use the dependencies locally.
Once the pipeline has successfully released the new versions and created the `index.yaml` in the `gh-pages` branch, I'll add another PR to switch back to the upstream repository again.
In the first action run for #20 (https://github.com/firefly-iii/kubernetes/runs/5256468777?check_suite_focus=true), the charts were released (see e.g. [importer-1.1.0](https://github.com/firefly-iii/kubernetes/releases/tag/importer-1.1.0)), but as the `gh-pages` branch didn't exist, it could not push the `index.yaml` to the `gh-pages` branch.
The re-run (https://github.com/firefly-iii/kubernetes/runs/5258243083?check_suite_focus=true) then checked the current chart versions against the existing …
=> chore: bump versions and revert to local files

.gitignore
- git now ignores `Chart.lock` files that are generated during local testing. We can safely do so as we have to assume trust between the charts anyway as they are all in the same repository.
@JC5
=> chore: ignore Chart.lock

charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii-stack/README.md
Follow up for #22.
This moves back to upstream versions of the dependencies. This decouples the charts so that we can develop them without breaking the `firefly-iii-stack` chart immediately.
@JC5
=> chore: switch to upstream dependencies

.github/workflows/lint-and-release.yml, charts/README.md, charts/firefly-db/Chart.yaml, charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii/Chart.yaml, charts/importer/Chart.yaml, ct.yaml
- Adds metadata to all charts (for more information and to have a valid Chart.yaml)
- Uses the [`ct` tool](https://github.com/helm/chart-testing) to lint charts when they change. This also checks that chart versions are bumped when changes are introduced.
- Adds information about the versioning used
@JC5
=> test/docs/feat: add Metadata, automatic linting and versioning documentation

.github/workflows/helm-docs.yml, charts/README.md, charts/firefly-db/Chart.yaml, charts/firefly-db/README.md, charts/firefly-db/README.md.gotmpl, charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii-stack/README.md, charts/firefly-iii-stack/README.md.gotmpl, charts/firefly-iii/Chart.yaml, charts/firefly-iii/README.md, charts/firefly-iii/README.md.gotmpl, charts/importer/Chart.yaml, charts/importer/README.md, charts/importer/README.md.gotmpl
This adds a `README.md.gotmpl` template for each chart and introduces a `Helm Docs` GitHub action that automatically regenerates documentation.
@JC5
=> docs: add helm-docs

charts/firefly-db/Chart.yaml, charts/firefly-db/README.md, charts/firefly-db/templates/firefly-db-deploy.yml, charts/firefly-db/templates/firefly-db-pvc.yml, charts/firefly-db/values.yaml, charts/firefly-iii/Chart.yaml, charts/firefly-iii/README.md, charts/firefly-iii/templates/deployment.yaml, charts/firefly-iii/templates/pvc.yaml, charts/firefly-iii/values.yaml
- One can specify existingClaims for the database and the main chart
- One can now specify an existing secret for the database and the main chart
@JC5 @morremeyer
=> Allow using existing claims and secrets in db and main

charts/firefly-iii/templates/deployment.yaml
- Fix k8s deployment health check
- Add startup probe to give the app 5m to start up, this ensures that the container does not go in a crash loop due to not having sufficient time to start up.
@JC5
=> Fix deployment health checks.

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/pvc.yaml
To create the pvc, the existing claim name is supposed to be equal to empty. Right now, it's expected that it's not equal to empty for the pvc to be generated.
=> fix: existing claim should be empty for pvc creation

kustomize/firefly-iii.yaml
Upon debugging why I lost an attachment after a deployment restart, I came upon a possibly wrong path for the upload volume mount.
Changing it from /var/www/html/storage/upload solved the problem for me and the data now survives a deployment restart.
- mountPath to /var/www/html/storage/upload in firefly-iii.yaml
=> Wrong volume path for uploaded files

charts/importer/Chart.yaml, charts/importer/templates/configmap.yaml, charts/importer/templates/deployment.yaml, charts/importer/values.yaml
- add the ability to configure env variables for the importer (For nordigen, spectre, ...)
=> feat: add env vars configurable for importer

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/cronjob.yaml, charts/firefly-iii/values.yaml
- Adds `secretKey` to the cronjob auth section with a default value of `token`
- Changes the class key to storageClassName under the persistence section.
- Bumps the firefly-iii chart version to 1.3.3
=> feat: fix and impove some values.yaml options

charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii-stack/README.md
Changes in this pull request: Updates the firefly-iii and importer charts to current versions.
=> chore: bump chart versions for firefly-iii-stack

.github/CODEOWNERS
Hey @JC5, hey everyone else!
Over the last year, I've contributed to the helm charts at https://github.com/firefly-iii/kubernetes more or less frequently since I was using Firefly III for a while. 
I started maintaining the charts since @JC5 is not running Kubernetes himself.
However, I stopped using Firefly III a while ago. While I love giving back to the community, over the last few months I've worked on reducing my responsibilities among different organizations and projects since I need to focus on myself for a while.
With that, maintaining the charts for Firefly III is one of the things I will stop doing. I'll finish up reviewing and merging #51 and will leave the decision about removing my access (or not) to @JC5.
Thanks for writing and maintaining Firefly III to @JC5, it really …
=> Stepping down as maintainer

.gitignore, charts/firefly-db/Chart.yaml, charts/firefly-db/templates/backup.tpl, charts/firefly-db/templates/firefly-backup-pvc.yml, charts/firefly-db/templates/firefly-db-backup-job.yml, charts/firefly-db/templates/firefly-db-cron-backup.yml, charts/firefly-db/templates/firefly-db-deploy.yml, charts/firefly-db/templates/firefly-db-restore-job.yml, charts/firefly-db/values.yaml
The current backup target with the HTTP endpoint is not very well documented, and there is no standard tooling for this. This PR adds an additional backup target implemented by a second PVC. This is self-contained and should make it easy to rollout the firefly-iii stack chart without any additional infrastructure
- Add PVC backup target for postgresql
- Refactor backup job code for increased code reuse
=> Add a pvc based backup target

charts/firefly-iii/Chart.yaml, charts/firefly-iii/README.md, charts/firefly-iii/templates/deployment.yaml, charts/firefly-iii/templates/secret.yaml, charts/firefly-iii/values.yaml
User can use helm secrets plugin to pass encrypted values file.
- new `secrets` section in `values.yaml` - sensitive env variables can be stored in Secret rather than in ConfigMap
- optional, only created when `config.existingSecret` is not used, making it backwards compatible.
=> feat: add support for creating Secret to store sensitive env variables

kustomize/ingress-firefly-iii-cron.yaml
To apply the kustomize workflow to my kube cluster I had to update the cron api version
Thanks for the cool software 
update to final release of cron api
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125
update api reference to final from beta1
- 
- 
-
=> update cron resource to use new api

charts/firefly-iii/Chart.yaml, charts/firefly-iii/README.md, charts/firefly-iii/templates/deployment.yaml, charts/firefly-iii/values.yaml
Fixes issue [#8075](https://github.com/firefly-iii/firefly-iii/issues/8075)
- Bumped version of `firefly-iii` helm chart to 1.5
- Added `extraVolumes` and `extraVolumeMounts` to `values.yaml`
- Added some documentation about how to use these options
=> add extraVolumes, extraVolumeMounts to helm chart

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/_helpers.tpl, charts/firefly-iii/templates/secret.yaml, charts/firefly-iii/values.yaml
Fixes issue: When I tried to install (with helm install) latest of firefly-iii and latest of firefly-db they were not working together automatically.
- DB_HOST now refers to the service name (firefly-db) and app can communicate with DB
- APP_KEY is created automatically as a random 32 long string as requested by the app
- new changes were tested with new docker image version and are working, so I also updated the image to use the latest available
=> Fix connection to firefly-db:0.2.1 and updated firefly-iii docker image 5.6.14 -> 6.1.1

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/_helpers.tpl, charts/firefly-iii/templates/secret-app-key.yaml, charts/firefly-iii/values.yaml
When using certain GitOps systems, the app-key secret is regenerated with every check. This PR allows a user to pre-define the value for `APP_KEY` in the chart values.
Use case: ArgoCD uses `helm template` to generate manifests and compares these to the deployed resources. As this command does not directly contacts the kubernetes API, the lookup value for the app-key secret (as defined in the `_helpers.tpl`) results in the value for `APP_KEY` to change on every sync/refresh.
Proposed changes in this pull request:
- Changes to `values.yaml`:
- Adds a new key under `secrets.appKey` that allows you to define the value for `APP_KEY`. This is commented by default
- Adds help on how to generate the `APP_KEY` value
- Changes to `_helpers.tpl`:
- Changes the check for the presence of the app-key …
=> Fix: Allow APP_KEY to be pre-defined

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/_helpers.tpl, charts/firefly-iii/values.yaml
When adding `APP_KEY` as a chart value, the validation for the length of the string inadvertingly added a newline and 2 spaces to the base64-encoded string.
This results in the bootstrapping process not to work, due to a misconfigured `APP_KEY`.
This PR resolves this.
=> Fix APP_KEY validation to not include newline and whitespace

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/deployment.yaml
This will cause the firefly-iii pod to be restarted, when the configmap changes.
=> Fix pod not restarted when config changes

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/deployment.yaml, charts/firefly-iii/values.yaml
- Introduce a configuration option to customize the update strategy. This enhancement is particularly beneficial for scenarios involving ReadWriteOnce (RWO) PersistentVolumeClaims (PVCs), where a PVC can be mounted by only one Pod at a time.
=> feat: add possibility to change update strategy

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/deployment.yaml
- add another annotation (`checksum/secret`) to the deployment template with the checksum of the secret.yaml file to ensure the pod is redeployed after a secret change.
=> fix: add annotation with checksum of secret

charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii-stack/README.md, charts/firefly-iii-stack/values.yaml
Fixes issue # [8651](https://github.com/firefly-iii/firefly-iii/issues/8651)
- Remove hardcoded value of storageClass for the db chart inside the stack chart
- Remove ReadWriteMany accessMode hardcode as well, as this will also depend on if the storageClass used supports it
=> no longer hard code storageClass and don't assume RWX

charts/firefly-db/Chart.yaml, charts/firefly-db/README.md, charts/firefly-db/templates/backup.tpl
If the postgres version in alpine repo mismatches the one of the main container the dump fails.
can be tested with values:
```yaml
firefly-db:
image:
repository: postgres
tag: 16.3-alpine
```
possible problem: if main image is not alpine and backup destination is http the curl install fails
=> fix: diffrent postgres versions in main container and backup Job

charts/firefly-db/Chart.yaml, charts/firefly-db/templates/backup.tpl, charts/firefly-db/templates/firefly-db-cm.yml, charts/firefly-db/templates/firefly-db-restore-job.yml, charts/firefly-db/values.yaml
Database backup job errors to authenticate to database when DB has been configured using `.Values.configs.existingSecret`.
When overriding the credentials using an existing secret that contains different values than the ones present on the default ConfigMap, the job will fail to authenticate the database.
```yaml
firefly-db:
configs:
existingSecret: firefly-iii # Variables for, DB*, and POSTGRES* are not  using default values.
```
```bash
OK: 143 MiB in 36 packages
creating backup file
pg_dump: error: connection to database "firefly" failed: FATAL:  password authentication failed for user "firefly"
```
As [templated here](https://github.com/firefly-iii/kubernetes/blob/main/charts/firefly-db/templates/firefly-db-deploy.yml#L26-L32), the database deployments load environments variable from …
=> Use environment variables from secret on database job.

charts/firefly-iii/Chart.yaml, charts/firefly-iii/templates/deployment.yaml, charts/firefly-iii/values.yaml
~Fixes issue # (if relevant)~
- Moved `livenessProbe`, `readinessProbe` and `startupProbe` to values
- Increased Helm Chart version
I discovered that on low-end devices such as the Raspberry Pi the container takes quite a lot of time to start up and therefore, after just 300 seconds, the container is being marked as not ready / unhealthy.
=> Make probes configurable

charts/firefly-db/README.md, charts/firefly-db/templates/backup.tpl, charts/firefly-db/templates/firefly-db-backup-job.yml, charts/firefly-db/templates/firefly-db-cron-backup.yml, charts/firefly-db/values.yaml
This PR fixes issue [#10628](https://github.com/firefly-iii/firefly-iii/issues/10628).
- Chart installation will fail if key `backup.destinaton` is set to `http` and `BACKUP_URL` is set to `""`.
- Defaults `backup.destination` key to `pvc`.
- Allows backup job to complete if `http` backup upload fails. Dump can still be recovered from the pvc.
=> Fix helm firefly db http backup job with default values

charts/firefly-iii-stack/Chart.yaml, charts/firefly-iii-stack/README.md, charts/firefly-iii/Chart.yaml, charts/firefly-iii/README.md, charts/importer/Chart.yaml, charts/importer/README.md, charts/importer/values.yaml, kustomize/firefly-iii-importer.yaml, kustomize/firefly-iii.yaml
Fixes issue # (if relevant) None
Update core to 6.2.21
Update data-importer to 1.7.8
Since there's a minor update on data-importer, I bumped the minor also for the importer chart to 1.5.0
=> Bump core and data-importer versions
