firefly-iii/kubernetes

firefly-iii.yaml

Fixed firefly container to get requests from port 8080

---

ingress-firefly-iii-cron.yaml
kustomization.yaml

Fixes issue https://github.com/firefly-iii/firefly-iii/issues/5278
- Added crnojob resource
- Added static docker token
@JC5

added cronjob resources

---

kustomization.yaml

Fixing references to cron and importer
-  fixed the references in kustomization.yaml according to previous renaming
@JC5

Update kustomization.yaml fixing references

---

kustomization.yaml

- Fixed naming to reflect filename (throws error by currently, fixes that)
@JC5

Fixed naming to reflect filename

---

ingress-firefly-iii-importer.yaml

Adds annotations for NGINX ingress as comments.

Add annotations for NGINX ingress

---

charts/firefly-db/Chart.yaml
charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii/Chart.yaml
charts/importer/Chart.yaml

I apparently can't write my own username correctly 😞 
@JC5

docs: morremeyer is not named morre

---

charts/firefly-iii/Chart.yaml
charts/firefly-iii/README.md

Retroactively bumps the version for #33.
@JC5

chore: bump version

---

charts/firefly-iii/Chart.yaml
charts/firefly-iii/README.md
charts/firefly-iii/README.md.gotmpl
charts/firefly-iii/templates/deployment.yaml
charts/firefly-iii/values.yaml

Fixes issue https://github.com/firefly-iii/firefly-iii/issues/6066
- Adds a `config.envValueFrom` setting that allows to configure additional environment variables from ConfigMaps und Secrets

feat: add envValueFrom

---

charts/firefly-iii/Chart.yaml
charts/firefly-iii/README.md
charts/firefly-iii/README.md.gotmpl
charts/firefly-iii/templates/deployment.yaml

Same changes as #38 but in helm files and readme for volume mount

wrong volume path for uploaded files

---

charts/firefly-iii/Chart.yaml
charts/firefly-iii/README.md
charts/firefly-iii/templates/pvc.yaml

Resolves https://github.com/firefly-iii/firefly-iii/issues/6078.

fix: set accessModes from values

---

charts/firefly-iii-stack/Chart.yaml

Update the stack chart to the right importer chart version

fix: update chart stack version

---

charts/importer/Chart.yaml
charts/importer/README.md
charts/importer/templates/deployment.yaml
charts/importer/templates/secret-files.yaml
charts/importer/values.yaml

Fixes issue https://github.com/firefly-iii/firefly-iii/issues/6195 
Changes in this pull request: 
* add support for arbitrary volumes
* add support for directly mounting files via a secret

feat: add volume mounting

---

charts/firefly-iii-stack/Chart.yaml

chore: update main chart to update dependencies version

bump dependent chart version

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii-stack/README.md

chore: bump chart versions for firefly-iii-stack

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii-stack/README.md

Sloppy, ignore a lint check.

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii/Chart.yaml
charts/firefly-iii/templates/hpa.yaml

Update HPA to v2 for firefly-iii

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii-stack/README.md
charts/firefly-iii/Chart.yaml
charts/firefly-iii/README.md
charts/firefly-iii/values.yaml
charts/importer/Chart.yaml
charts/importer/README.md
charts/importer/values.yaml
kustomize/firefly-iii-importer.yaml
kustomize/firefly-iii.yaml

- Update core to 6.1.21
- Update data-importer to 1.5.6

Bump core and data-importer versions

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii-stack/README.md

This MR bumps the subchart versions in the stack chart.

Update firefly-iii-stack chart dependencies.

---

charts/firefly-iii/Chart.yaml
charts/firefly-iii/templates/cronjob.yaml
charts/firefly-iii/templates/deployment.yaml
charts/firefly-iii/values.yaml

update images:
- fireflyiii/core `6.1.21` -> `6.2.5`
- curlimages/curl: `7.81.0` -> `8.12.0`
Additional changes:
- add option for registry (current default docker.io)
- add option to overwrite registry and pullPolicy for all images
- move image version to Chart.yaml "AppVersion"

fix: update images and improve values for image

---

charts/firefly-db/Chart.yaml
charts/firefly-db/README.md
kustomize/firefly-iii.yaml

This PR fixes issue # (if relevant).
-
-
-

Change storage

---

charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii-stack/README.md

This PR fixes issue # (if relevant).
-
-
-

Change yaml

---

.github/workflows/lint-and-release.yml
charts/firefly-db/Chart.yaml
charts/firefly-iii-stack/Chart.yaml
charts/firefly-iii/Chart.yaml
charts/importer/Chart.yaml

This PR fixes issue # (if relevant).
- Change subChart repositories to the local file paths. Forcing more alignment in the subCharts & parentChart
- All changes in subCharts will also require a version bump in the parentChart
- Changes to the pipeline. Running chart testing paralel to get easier insights in where the issue occurs
- Solves https://github.com/firefly-iii/firefly-iii/issues/10557

Fix pipeline
